-- AlterTable
ALTER TABLE `notifications` MODIFY `f_type` ENUM('FOLLOW', 'BEWT', 'PURCHASE', 'CHAT', 'SCOUT', 'ORDER', 'BEWTS_JOIN_REQUEST', 'BEWTS_JOIN_APPROVED', 'BEWTS_JOIN_DECLINED', 'SYSTEM') NOT NULL;
